import gspread
import pandas as pd
from gspread_dataframe import set_with_dataframe
import sqlite3
import os
from datetime import datetime
import logging

# Import configuration variables from config.py
from config import (
    GOOGLE_SHEET_ID,
    DATABASE_PATH,
    SERVICE_ACCOUNT_KEY_PATH,
    GOOGLE_SHEET_WORKSHEET_NAME
)

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# --- YOUR SPECIFIC COLUMN DEFINITIONS & ORDER ---
SHEET_COLUMN_ORDER = [
    "variant_image_formula",    # This will be the IMAGE() formula column (Column A)
    "snap_card_name",
    "variant_url",              # The actual URL for the variant image
    "inker",
    "sketcher",
    "colorist",
    "ReleaseDate",
    "full_description",
    "comic_title",
    "comic_year",
    "issue_number",
    "manual_status",
    "is_original_commission",
    "commission_image_url",     # The actual URL for the commission image
    "commission_image_formula", # This will be the IMAGE() formula for commission
    "identified_date",
    "manual_notes",
    "reference_links",
    "variant_id",               # Internal DB ID, merge key
    "vid",                      # Snap's internal variant ID
    "comic_cover_link",         # The actual URL for the comic cover image
    "comic_cover_image_formula",# This will be the IMAGE() formula for comic cover
    "marvel_link",
    "marvel_unlimited_link",
    "amazon_link",
    "source_type",
    "source_url_type"
]

# Define which columns are primarily controlled by the database
# These will always be overwritten by DB values if there's a discrepancy
# Note: Formula columns are NOT in this list as they are generated by the script.
DB_CONTROLLED_COLUMNS = [
    "snap_card_name",
    "variant_url",
    "inker",
    "sketcher",
    "colorist",
    "ReleaseDate",
    "full_description",
    "variant_id",
    "vid",
    "comic_cover_link",
    "marvel_link",          # MOVED: Now DB is source of truth for these links
    "marvel_unlimited_link",# MOVED: Now DB is source of truth for these links
    "amazon_link",          # MOVED: Now DB is source of truth for these links
]

# Define which columns can be manually edited in the Google Sheet and should be preserved
# If a value exists in the sheet for these, it will take precedence over a blank/default DB value
SHEET_EDITABLE_COLUMNS = [
    "comic_title",
    "comic_year",
    "issue_number",
    "manual_status",
    "is_original_commission",
    "commission_image_url", # MOVED: Now Sheet value takes precedence (but won't sync TO DB by THIS script)
    "identified_date",
    "manual_notes",
    "reference_links",
    "source_type",
    "source_url_type"
]

# --- Validation (Good Practice) ---
combined_defined_cols = set(DB_CONTROLLED_COLUMNS + SHEET_EDITABLE_COLUMNS)
non_formula_sheet_cols = [col for col in SHEET_COLUMN_ORDER if "_formula" not in col]

if not combined_defined_cols == set(non_formula_sheet_cols):
    missing_in_categorization = set(non_formula_sheet_cols) - combined_defined_cols
    extra_in_categorization = combined_defined_cols - set(non_formula_sheet_cols)
    if missing_in_categorization:
        logging.warning(f"Warning: Columns in SHEET_COLUMN_ORDER (non-formula) not categorized as DB_CONTROLLED or SHEET_EDITABLE: {missing_in_categorization}")
    if extra_in_categorization:
        logging.warning(f"Warning: Columns in DB_CONTROLLED or SHEET_EDITABLE not found in SHEET_COLUMN_ORDER (excluding formulas): {extra_in_categorization}")

if set(DB_CONTROLLED_COLUMNS).intersection(set(SHEET_EDITABLE_COLUMNS)):
    logging.error("ERROR: DB_CONTROLLED_COLUMNS and SHEET_EDITABLE_COLUMNS have overlapping fields. Please correct them.")
    exit(1)


# --- DATABASE AND SHEETS CLIENT FUNCTIONS ---

def get_db_connection():
    """Establishes and returns a connection to the SQLite database."""
    try:
        conn = sqlite3.connect(DATABASE_PATH)
        conn.row_factory = sqlite3.Row
        logging.info(f"Connected to database: {DATABASE_PATH}")
        return conn
    except sqlite3.Error as e:
        logging.error(f"Database connection error: {e}")
        raise

def get_sheets_client():
    """
    Authenticates with Google Sheets using a service account.
    Returns the gspread Client object.
    """
    if not os.path.exists(SERVICE_ACCOUNT_KEY_PATH):
        logging.error(f"Service account key file not found at: {SERVICE_ACCOUNT_KEY_PATH}")
        raise FileNotFoundError(f"Missing service account key at {SERVICE_ACCOUNT_KEY_PATH}")

    try:
        gc = gspread.service_account(filename=SERVICE_ACCOUNT_KEY_PATH)
        logging.info("Successfully authenticated with Google Sheets.")
        return gc
    except Exception as e:
        logging.error(f"Failed to authenticate with Google Sheets: {e}")
        raise

# --- MAIN SYNC FUNCTION ---

def sync_data_to_google_sheet():
    """
    Synchronizes data from the SQLite database to the Google Sheet.
    Reads existing sheet data, merges with database data using 'variant_id' as key,
    prioritizing DB for DB-controlled columns and Sheet for user-editable columns,
    then uploads the combined data.
    """
    logging.info("Starting data synchronization to Google Sheet...")

    gc = get_sheets_client()
    conn = None
    try:
        conn = get_db_connection()

        spreadsheet = gc.open_by_key(GOOGLE_SHEET_ID)
        worksheet = spreadsheet.worksheet(GOOGLE_SHEET_WORKSHEET_NAME)
        logging.info(f"Connected to Google Sheet: {spreadsheet.url}")

        # 1. Read existing data from Google Sheet
        try:
            sheet_data = worksheet.get_all_records()
            df_sheet = pd.DataFrame(sheet_data)
            logging.info(f"Read {len(df_sheet)} rows from Google Sheet.")
            if not df_sheet.empty:
                if 'variant_id' in df_sheet.columns:
                    df_sheet['variant_id'] = df_sheet['variant_id'].astype(str)
                else:
                    logging.warning("Google Sheet does not contain 'variant_id' column. It will be added from DB data.")
            else:
                logging.info("Google Sheet is empty or contains only headers.")

        except Exception as e:
            logging.warning(f"Could not read existing sheet data as records (might be empty or malformed): {e}. Proceeding with an empty sheet DataFrame.")
            df_sheet = pd.DataFrame(columns=SHEET_COLUMN_ORDER)


        # 2. Fetch data from the database
        # Only query columns that are explicitly DB-controlled and are actual database columns
        # This prevents "no such column" errors for columns that are only in the sheet.
        db_cols_to_query = [col for col in DB_CONTROLLED_COLUMNS if col not in ['variant_image_formula', 'commission_image_formula', 'comic_cover_image_formula']]

        # Ensure essential merge key 'variant_id' is always in the query if not already.
        if 'variant_id' not in db_cols_to_query:
            db_cols_to_query.append('variant_id')

        select_clause = ", ".join([f"COALESCE(v.{col}, '') AS {col}" for col in db_cols_to_query])

        if not select_clause:
            logging.error("No valid columns to query from the database. Please check DB_CONTROLLED_COLUMNS.")
            return

        query = f"""
        SELECT
            {select_clause}
        FROM Variants v
        ORDER BY variant_id;
        """
        df_db = pd.read_sql_query(query, conn)
        logging.info(f"Fetched {len(df_db)} rows from SQLite database.")

        # --- Data Post-processing for DB DataFrame ---
        if not df_db.empty:
            if 'ReleaseDate' in df_db.columns:
                df_db['ReleaseDate'] = pd.to_numeric(df_db['ReleaseDate'], errors='coerce')
                df_db['ReleaseDate'] = df_db['ReleaseDate'].apply(
                    lambda ts: datetime.utcfromtimestamp(ts).strftime('%m/%d/%y') if pd.notna(ts) else ''
                )

            if 'variant_id' in df_db.columns:
                df_db['variant_id'] = df_db['variant_id'].astype(str)
            else:
                logging.error("Database query did not return 'variant_id' column. This is critical for merging.")
                return

            # Ensure all columns from SHEET_COLUMN_ORDER are present in df_db, initializing missing ones as blank
            # This handles columns that are SHEET_EDITABLE but might not be in the DB query
            for col in SHEET_COLUMN_ORDER:
                if col not in df_db.columns:
                    df_db[col] = ''

        else:
            logging.warning("No data found in the database.")


        # 3. Merge/Combine DataFrames using 'variant_id'
        merged_df = pd.merge(df_db, df_sheet, on='variant_id', how='outer', suffixes=('_db', '_sheet'))
        logging.info(f"Merged DataFrame has {len(merged_df)} rows after outer join on 'variant_id'.")


        final_rows = []
        for _, row in merged_df.iterrows():
            new_row = {}
            for col in SHEET_COLUMN_ORDER:
                if col == 'variant_id':
                    new_row[col] = row['variant_id']
                elif col in DB_CONTROLLED_COLUMNS:
                    db_val = row.get(f'{col}_db')
                    sheet_val = row.get(f'{col}_sheet')
                    if pd.notna(db_val) and db_val != '':
                        new_row[col] = db_val
                    elif pd.notna(sheet_val) and sheet_val != '':
                        new_row[col] = sheet_val
                    else:
                        new_row[col] = ''
                elif col in SHEET_EDITABLE_COLUMNS:
                    sheet_val = row.get(f'{col}_sheet')
                    db_val = row.get(f'{col}_db')
                    if pd.notna(sheet_val) and sheet_val != '':
                        new_row[col] = sheet_val
                    elif pd.notna(db_val) and db_val != '':
                        new_row[col] = db_val
                    else:
                        new_row[col] = ''
                elif '_formula' in col:
                    new_row[col] = ''
                else:
                    db_val = row.get(f'{col}_db')
                    sheet_val = row.get(f'{col}_sheet')
                    if pd.notna(db_val) and db_val != '':
                        new_row[col] = db_val
                    elif pd.notna(sheet_val) and sheet_val != '':
                        new_row[col] = sheet_val
                    else:
                        new_row[col] = ''

            final_rows.append(new_row)

        final_df = pd.DataFrame(final_rows)
        final_df = final_df.reindex(columns=SHEET_COLUMN_ORDER, fill_value='')

        logging.info(f"Final merged DataFrame prepared for upload contains {len(final_df)} rows.")

        # 4. Upload DataFrame to Google Sheet
        if not final_df.empty:
            logging.info(f"Uploading {len(final_df)} rows to Google Sheet...")
            worksheet.clear()
            set_with_dataframe(worksheet, final_df, include_index=False)
            logging.info("Data successfully synchronized and exported to Google Sheet.")
        else:
            logging.warning("Final DataFrame is empty after merge. Google Sheet will be cleared.")
            worksheet.clear()


    except gspread.exceptions.SpreadsheetNotFound:
        logging.error(f"Google Sheet with ID '{GOOGLE_SHEET_ID}' not found. "
                      "Please check the ID in config.py and ensure the service account has access.")
    except gspread.exceptions.WorksheetNotFound:
        logging.error(f"Worksheet '{GOOGLE_SHEET_WORKSHEET_NAME}' not found. "
                      "Please ensure the worksheet name in config.py is correct and exists in your spreadsheet.")
    except Exception as e:
        logging.error(f"An unexpected error occurred during sync: {e}", exc_info=True)
    finally:
        if conn:
            conn.close()

# --- SHEET FORMATTING AND FORMULAS ---

def apply_sheet_formatting_and_formulas():
    """
    Applies formatting (row height, column width) and IMAGE formulas to the Google Sheet.
    This runs AFTER the data has been uploaded.
    """
    logging.info("Applying sheet formatting and IMAGE formulas...")

    gc = get_sheets_client()
    try:
        spreadsheet = gc.open_by_key(GOOGLE_SHEET_ID)
        worksheet = spreadsheet.worksheet(GOOGLE_SHEET_WORKSHEET_NAME)
        logging.info(f"Connected to Google Sheet for formatting: {spreadsheet.url}")

        requests = []

        # Set header row height to 20px (Row 1 is index 0)
        requests.append({
            "updateDimensionProperties": {
                "range": {
                    "sheetId": worksheet.id,
                    "dimension": "ROWS",
                    "startIndex": 0,
                    "endIndex": 1 # Only applies to the first row
                },
                "properties": {
                    "pixelSize": 20
                },
                "fields": "pixelSize"
            }
        })
        logging.info("Added request to set header row height to 20px.")

        # Set all other row heights to 100px (starting from Row 2, which is index 1)
        requests.append({
            "updateDimensionProperties": {
                "range": {
                    "sheetId": worksheet.id,
                    "dimension": "ROWS",
                    "startIndex": 1 # Starts from the second row
                },
                "properties": {
                    "pixelSize": 100
                },
                "fields": "pixelSize"
            }
        })
        logging.info("Added request to set data row heights to 100px.")


        # Freeze the first row (header row)
        sheet_properties = spreadsheet.fetch_sheet_metadata(params={'fields': 'sheets.properties'}).get('sheets', [])
        current_frozen_row_count = 0
        for s in sheet_properties:
            if s.get('properties', {}).get('sheetId') == worksheet.id:
                current_frozen_row_count = s.get('properties', {}).get('gridProperties', {}).get('frozenRowCount', 0)
                break

        if current_frozen_row_count != 1:
            requests.append({
                "updateSheetProperties": {
                    "properties": {
                        "sheetId": worksheet.id,
                        "gridProperties": {
                            "frozenRowCount": 1
                        }
                    },
                    "fields": "gridProperties.frozenRowCount"
                }
            })
            logging.info("Added request to freeze header row.")
        else:
            logging.info("Header row already frozen.")


        headers = worksheet.row_values(1)
        image_formula_updates = []

        # Define image columns and their corresponding URL source columns, and desired width
        image_columns_to_process = [
            ("variant_image_formula", "variant_url", 100),
            ("commission_image_formula", "commission_image_url", 100),
            ("comic_cover_image_formula", "comic_cover_link", 100),
        ]

        for formula_col_name, url_col_name, desired_width_px in image_columns_to_process:
            try:
                # Use gspread.utils.find_row_cols_with_headers for more robust column finding if needed
                formula_col_0_idx = headers.index(formula_col_name)
                formula_col_1_idx = formula_col_0_idx + 1
                # This should work after gspread update
                formula_col_letter = gspread.utils.get_column_letter(formula_col_1_idx)

                url_col_0_idx = headers.index(url_col_name)
                url_col_1_idx = url_col_0_idx + 1
                all_url_values = worksheet.col_values(url_col_1_idx)

                logging.info(f"Processing image column: '{formula_col_name}' (Column {formula_col_letter})")

                # Set column width for the formula column
                requests.append({
                    "updateDimensionProperties": {
                        "range": {
                            "sheetId": worksheet.id,
                            "dimension": "COLUMNS",
                            "startIndex": formula_col_0_idx,
                            "endIndex": formula_col_0_idx + 1
                        },
                        "properties": {
                            "pixelSize": desired_width_px
                        },
                        "fields": "pixelSize"
                    }
                })
                logging.info(f"Added request to set column '{formula_col_name}' width to {desired_width_px}px.")

                num_data_rows = len(all_url_values) - 1

                if num_data_rows > 0:
                    for row_idx_1_based in range(2, num_data_rows + 2):
                        url_to_use = all_url_values[row_idx_1_based - 1]
                        if url_to_use and not url_to_use.strip().upper().startswith('=IMAGE('):
                            image_formula_updates.append({
                                'range': gspread.utils.rowcol_to_a1(row_idx_1_based, formula_col_1_idx),
                                'values': [[f'=IMAGE("{url_to_use}")']]
                            })
                else:
                    logging.info(f"No data rows found to apply IMAGE formulas for '{formula_col_name}'.")

            except ValueError:
                logging.warning(f"Warning: Missing column '{formula_col_name}' or '{url_col_name}' in sheet headers. Skipping IMAGE formula application for this set.")
            except Exception as e:
                logging.error(f"Error processing image column '{formula_col_name}': {e}", exc_info=True)

        if image_formula_updates:
            worksheet.batch_update(image_formula_updates)
            logging.info("All IMAGE formulas successfully applied to relevant columns.")
        else:
            logging.info("No IMAGE formulas applied (either no data or columns not found).")

        if requests:
            spreadsheet.batch_update({"requests": requests})
            logging.info("Batch formatting updates (row height, column width, freeze row) applied.")
        else:
            logging.info("No new sheet formatting updates required (likely already applied).")


    except gspread.exceptions.SpreadsheetNotFound:
        logging.error(f"Google Sheet with ID '{GOOGLE_SHEET_ID}' not found. "
                      "Please check the ID in config.py and ensure the service account has access.")
    except gspread.exceptions.WorksheetNotFound:
        logging.error(f"Worksheet '{GOOGLE_SHEET_WORKSHEET_NAME}' not found. "
                      "Please ensure the worksheet name in config.py is correct and exists in your spreadsheet.")
    except Exception as e:
        logging.error(f"An unexpected error occurred during formatting: {e}", exc_info=True)


if __name__ == "__main__":
    if not GOOGLE_SHEET_ID or GOOGLE_SHEET_ID == 'YOUR_GOOGLE_SHEET_ID_HERE':
        logging.error("GOOGLE_SHEET_ID is not set or is still a placeholder in config.py.")
        exit(1)
    if not DATABASE_PATH or not os.path.exists(DATABASE_PATH):
        logging.error(f"DATABASE_PATH is not set or database file not found at: {DATABASE_PATH}. Please check config.py and ensure the database exists.")
        exit(1)
    if not SERVICE_ACCOUNT_KEY_PATH or not os.path.exists(SERVICE_ACCOUNT_KEY_PATH):
        logging.error(f"SERVICE_ACCOUNT_KEY_PATH is not set or file not found at: {SERVICE_ACCOUNT_KEY_PATH}. Please check config.py and ensure the file exists.")
        exit(1)

    logging.info("Starting Google Sheet synchronization process...")
    sync_data_to_google_sheet()
    apply_sheet_formatting_and_formulas()
    logging.info("Google Sheet synchronization process completed.")